[build]
  functions = "functions"
  command = "yarn build && cp functions/export/lib/* node_modules/canvas/build/Release/"
  publish = "build"
  environment = { LD_LIBRARY_PATH = "" }

[[redirects]]
from = "/export"
to = "/.netlify/functions/export"
status = 200
force = true

[[redirects]]
from = "/share"
to = "/.netlify/functions/share"
status = 200
force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["canvas", "lzma"]
  included_files = [
    "./functions/export/xhr-sync-worker.js",
    "./functions/export/lib/*",
    "./functions/export/fonts/*",
  ]
